/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opencv_tuxin_detectanswersheets_AnswerSheetBase */

#ifndef _Included_com_opencv_tuxin_detectanswersheets_AnswerSheetBase
#define _Included_com_opencv_tuxin_detectanswersheets_AnswerSheetBase
#ifdef __cplusplus
extern "C" {
#endif
#undef com_opencv_tuxin_detectanswersheets_AnswerSheetBase_SUM_OF_QUESTIONS
#define com_opencv_tuxin_detectanswersheets_AnswerSheetBase_SUM_OF_QUESTIONS 54L
/*
 * Class:     com_opencv_tuxin_detectanswersheets_AnswerSheetBase
 * Method:    getAnswerSheetInfo
 * Signature: ([III)Lcom/opencv/tuxin/detectanswersheets/GetDataFromNative;
 */
JNIEXPORT jobject JNICALL Java_com_opencv_tuxin_detectanswersheets_AnswerSheetBase_getAnswerSheetInfo
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

/*
 * Class:     com_opencv_tuxin_detectanswersheets_AnswerSheetBase
 * Method:    getStudentAnswers
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_opencv_tuxin_detectanswersheets_AnswerSheetBase_getStudentAnswers
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat, jint);

/*
 * Class:     com_opencv_tuxin_detectanswersheets_AnswerSheetBase
 * Method:    getStudentNumbers
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_opencv_tuxin_detectanswersheets_AnswerSheetBase_getStudentNumbers
  (JNIEnv *, jobject, jintArray, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
